<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basecalculationmodel"
    nsURI="http://bhl.net/cdt/utilities/basecalculationmodel/" nsPrefix="net.bhl.cdt.utilities">
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EEnum units.ecore#//Quantity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType units.ecore#//Unit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EClass" instanceClassName="org.eclipse.emf.ecore.EClass"/>
</ecore:EPackage>
