<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes"
    nsURI="http://bhl.net/cdt/utilities/datatypes/" nsPrefix="net.bhl.cdt.utilities">
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="exchangemodel.ecore#//ExchangeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeafValue" abstract="true" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scalar" abstract="true" eSuperTypes="#//LeafValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatPointValue" eSuperTypes="#//Scalar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasuredValue" eSuperTypes="#//FloatPointValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType units.ecore#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//Scalar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//LeafValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula" eSuperTypes="#//StringValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeValues" eSuperTypes="#//DataType">
    <eOperations name="getDimensions">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//CompositeValues"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cells" eSuperTypes="#//CompositeValues"/>
</ecore:EPackage>
