<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelview"
    nsURI="http://bhl.net/cdt/model/modelview" nsPrefix="net.bhl.cdt.model.modelview">
  <eClassifiers xsi:type="ecore:EClass" name="DisciplineView" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//StructuralElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceTypes" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewLinks" upperBound="-1"
        eType="#//ViewLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" upperBound="-1"
        eType="#//SetExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewLink" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualParent" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualChild" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//SetExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//ComponentInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discipline" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpression" abstract="true" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetOperator" eSuperTypes="#//SetExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//SetOperators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="2"
        eType="#//SetExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetOperators">
    <eLiterals name="AND"/>
    <eLiterals name="OR"/>
    <eLiterals name="MINUS"/>
  </eClassifiers>
</ecore:EPackage>
