<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reporting" nsURI="http://net.bhl/cdt/reporting" nsPrefix="reporting">
  <eClassifiers xsi:type="ecore:EClass" name="Report" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Map" eType="#//ReportMap"
        eOpposite="#//ReportMap/Reports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Charts" upperBound="-1"
        eType="#//Chart" containment="true" eOpposite="#//Chart/Report" eKeys="../../net.bhl.cdt.model/model/model.ecore#//NamedElement/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSourceDefinitions"
        upperBound="-1" eType="#//DataSourceDefinition" containment="true" eOpposite="#//DataSourceDefinition/Report"
        eKeys="../../net.bhl.cdt.model/model/model.ecore#//NamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reports" upperBound="-1"
        eType="#//Report" containment="true" eOpposite="#//Report/Map" eKeys="../../net.bhl.cdt.model/model/model.ecore#//NamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportElement" abstract="true" interface="true"
      eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Chart" abstract="true" interface="true"
      eSuperTypes="#//ReportElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Title" lowerBound="1" eType="#//Label"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Report" eType="#//Report"
        eOpposite="#//Report/Charts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShowLegend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" eType="#//DataSource"
        containment="true" eOpposite="#//DataSource/Chart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart2D" abstract="true" eSuperTypes="#//Chart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="XAxis" lowerBound="1" eType="#//Axis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="YAxis" lowerBound="1" eType="#//Axis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart3D" eSuperTypes="#//Chart"/>
  <eClassifiers xsi:type="ecore:EClass" name="BarChart" eSuperTypes="#//Chart2D"/>
  <eClassifiers xsi:type="ecore:EClass" name="Axis" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement #//FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Label" lowerBound="1" eType="#//Label"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateAxis" eSuperTypes="#//Axis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FormatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerAxis" eSuperTypes="#//Axis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Family" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttChart" eSuperTypes="#//Chart2D">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskNameField" eType="#//DataField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StartDateField" eType="#//DataField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EndDateField" eType="#//DataField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Field" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceDefinition" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Member" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Report" eType="#//Report"
        eOpposite="#//Report/DataSourceDefinitions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Definition" lowerBound="1"
        eType="#//DataSourceDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Chart" eType="#//Chart"
        eOpposite="#//Chart/DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubSource" eType="#//DataSource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Filter" upperBound="-1"
        eType="#//DataSourceFilter" containment="true" eOpposite="#//DataSourceFilter/DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Groupings" upperBound="-1"
        eType="#//DataSourceGrouping" containment="true" eOpposite="#//DataSourceGrouping/DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceFilter" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" eType="#//DataSource"
        eOpposite="#//DataSource/Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FilterField" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FilterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubSource" eType="#//DataSource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceGrouping" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" eType="#//DataSource"
        eOpposite="#//DataSource/Groupings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GroupingField" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubSource" eType="#//DataSource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BubbleChart" eSuperTypes="#//Chart2D">
    <eStructuralFeatures xsi:type="ecore:EReference" name="XCoordinateField" eType="#//DataField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="YCoordinateField" eType="#//DataField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BubbleSizeField" eType="#//DataField"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
