<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reporting" nsURI="http://net.bhl/cdt/reporting" nsPrefix="reporting">
  <eClassifiers xsi:type="ecore:EClass" name="Report" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Map" eType="#//ReportMap"
        eOpposite="#//ReportMap/Reports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Charts" upperBound="-1"
        eType="#//Chart" containment="true" eOpposite="#//Chart/Report" eKeys="../../net.bhl.cdt.model/model/model.ecore#//NamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reports" upperBound="-1"
        eType="#//Report" containment="true" eOpposite="#//Report/Map" eKeys="../../net.bhl.cdt.model/model/model.ecore#//NamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportElement" abstract="true" interface="true"
      eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Chart" abstract="true" interface="true"
      eSuperTypes="#//ReportElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Title" lowerBound="1" eType="#//Label"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Report" eType="#//Report"
        eOpposite="#//Report/Charts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShowLegend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart2D" abstract="true" eSuperTypes="#//Chart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="XAxis" lowerBound="1" eType="#//Axis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="YAxis" lowerBound="1" eType="#//Axis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart3D" eSuperTypes="#//Chart"/>
  <eClassifiers xsi:type="ecore:EClass" name="BarChart" eSuperTypes="#//Chart2D"/>
  <eClassifiers xsi:type="ecore:EClass" name="Axis" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement #//FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Label" lowerBound="1" eType="#//Label"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Family" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//FontPropertyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttChart" eSuperTypes="#//Chart2D"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Member" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dimensions" upperBound="-1"
        eType="#//DataDimension"/>
  </eClassifiers>
</ecore:EPackage>
