<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cdtliterature" nsURI="http://www.bauhaus-luftfahrt.net/cdt/literature"
    nsPrefix="cdtliterature">
  <eClassifiers xsi:type="ecore:EClass" name="ALiteratureBase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//ALiteratureBase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isbn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inbook" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conference" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incollection" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inproceedings" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" upperBound="-1"
        eType="#//Article" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proceedings" eSuperTypes="#//ALiteratureBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="Techreport" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="institution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phdthesis" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="school" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Masterthesis" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="school" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unpublished" eSuperTypes="#//ALiteratureBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" upperBound="-1"
        eType="#//Article" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" upperBound="-1" eType="#//Book"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inbook" upperBound="-1"
        eType="#//Inbook" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conference" upperBound="-1"
        eType="#//Conference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incollection" upperBound="-1"
        eType="#//Incollection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inproceedings" upperBound="-1"
        eType="#//Inproceedings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proceedings" upperBound="-1"
        eType="#//Proceedings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="techreport" upperBound="-1"
        eType="#//Techreport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phdthesis" upperBound="-1"
        eType="#//Phdthesis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="masterthesis" upperBound="-1"
        eType="#//Masterthesis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unpublished" upperBound="-1"
        eType="#//Unpublished" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
