<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="formula" nsURI="http://bauhaus-luftfahrt.net/cdt/methods/formula"
    nsPrefix="formula">
  <eClassifiers xsi:type="ecore:EClass" name="FormulaRepository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formulas" upperBound="-1"
        eType="#//Formula" containment="true" eOpposite="#//Formula/repository"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantities" upperBound="-1"
        eType="#//Quantity" containment="true" eOpposite="#//Quantity/repository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula">
    <eOperations name="hasName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latexString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputParameter" eType="#//Quantity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputParameter" eType="#//Quantity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//FormulaRepository" eOpposite="#//FormulaRepository/formulas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass ../../net.bhl.cdt.literature.model/model/cdtliterature.ecore#//ALiteratureBase"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quantity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//FormulaRepository" eOpposite="#//FormulaRepository/quantities"/>
  </eClassifiers>
</ecore:EPackage>
