<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.bauhaus-luftfahrt.net/cdt" nsPrefix="net.bhl.cdt">
  <eSubpackages name="base" nsURI="http://www.bauhaus-luftfahrt.net/cdt/base" nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EClass" name="ANamedItem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AIdentifiableItem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelContainer" eSuperTypes="#//base/ANamedItem #//base/AIdentifiableItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedItems" upperBound="-1"
          eType="#//base/AModelContainerItem" containment="true" eOpposite="#//base/AModelContainerItem/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AModelContainerItem" abstract="true"
        eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//base/ModelContainer" eOpposite="#//base/ModelContainer/containedItems"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="data" nsURI="http://www.bauhaus-luftfahrt.net/cdt/data" nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EClass" name="AUnit" eSuperTypes="#//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//data/IParameter"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//data/IParameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IParameter" abstract="true" interface="true"
        eSuperTypes="#//base/ANamedItem #//base/AIdentifiableItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="IDataEntity" abstract="true" interface="true"
        eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//data/IParameter" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="quantities" nsURI="http://www.bauhaus-luftfahrt.net/cdt/quantities"
      nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EDataType" name="Length" instanceClassName="javax.measure.quantity.Length"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Distance" instanceClassName="javax.measure.quantity.Length"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Amount" instanceClassName="org.jscience.physics.amount.Amount">
      <eTypeParameters name="Q">
        <eBounds eClassifier="#//quantities/Quantity"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Unit" instanceClassName="javax.measure.unit.Unit">
      <eTypeParameters name="Q">
        <eBounds eClassifier="#//quantities/Quantity"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Quantity" instanceClassName="javax.measure.quantity.Quantity"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringParameter" eSuperTypes="#//data/IParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INumberParameter" abstract="true"
        interface="true" eSuperTypes="#//data/IParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="LengthParamenter" eSuperTypes="#//quantities/INumberParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eGenericType eClassifier="#//quantities/Amount">
          <eTypeArguments eClassifier="#//quantities/Length"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit">
        <eGenericType eClassifier="#//quantities/Unit">
          <eTypeArguments eClassifier="#//quantities/Length"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
