<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="files" nsURI="http://bhl.net/cdt/connector/files" nsPrefix="net.bhl.cdt.connector">
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsImporter" eSuperTypes="#//FileParser"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeometryImporter" eSuperTypes="#//FileParser"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileOperation" abstract="true" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//process/DesignOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileGenerator" abstract="true" eSuperTypes="#//FileOperation ../../net.bhl.cdt.model/model/model.ecore#//OperationWithInput"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileParser" abstract="true" eSuperTypes="#//FileOperation ../../net.bhl.cdt.model/model/model.ecore#//OperationWithOutput"/>
</ecore:EPackage>
