<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecturetools"
    nsURI="http://bhl.net/cdt/model/architecturetools" nsPrefix="net.bhl.cdt.architecturetools">
  <eClassifiers xsi:type="ecore:EClass" name="PowerConsumer" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getPowerConsumption" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerDemandView" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedConfigurations"
        upperBound="-1" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Configuration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Massive" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getMass" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="massParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoefficientInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getCoefficient" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coefficientParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WettedAreaInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getWettedArea" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wettedAreaParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceAreaInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getReferenceArea" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceAreaParameter"
        eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltitudeInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getAltitude" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altitudeParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getRange" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFCInterface" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//MappableComponentInterface">
    <eOperations name="getSFC" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SFCParameter" eType="ecore:EClass ../../net.bhl.cdt.model/model/model.ecore#//Parameter"/>
  </eClassifiers>
</ecore:EPackage>
