---------------------------------------------
Run case  1:  alpha 0.0  aileron 0.0

 alpha        ->  alpha        =   0.0
 beta         ->  beta         =   0.0
 pb/2V        ->  pb/2V        =   0
 qc/2V        ->  qc/2V        =   0
 rb/2V        ->  rb/2V        =   0
 aileron      ->  aileron      =   0.0


---------------------------------------------
Run case  2:  alpha 0.0  aileron 10.0

 alpha        ->  alpha        =   0.0
 beta         ->  beta         =   0.0
 pb/2V        ->  pb/2V        =   0
 qc/2V        ->  qc/2V        =   0
 rb/2V        ->  rb/2V        =   0
 aileron      ->  aileron      =   10.0


---------------------------------------------
Run case  3:  alpha 5.0  aileron 0.0

 alpha        ->  alpha        =   5.0
 beta         ->  beta         =   0.0
 pb/2V        ->  pb/2V        =   0
 qc/2V        ->  qc/2V        =   0
 rb/2V        ->  rb/2V        =   0
 aileron      ->  aileron      =   0.0


---------------------------------------------
Run case  4:  alpha 5.0  aileron 10.0

 alpha        ->  alpha        =   5.0
 beta         ->  beta         =   0.0
 pb/2V        ->  pb/2V        =   0
 qc/2V        ->  qc/2V        =   0
 rb/2V        ->  rb/2V        =   0
 aileron      ->  aileron      =   10.0
