
 ---------------------------------------------
 Run case  1:  alpha 0 ail 0                              

 alpha        ->  alpha       =   0.00000    
 beta         ->  beta        =   0.00000    
 pb/2V        ->  pb/2V       =   0.00000    
 qc/2V        ->  qc/2V       =   0.00000    
 rb/2V        ->  rb/2V       =   0.00000    
 aileron      ->  aileron     =   0.00000    



 ---------------------------------------------
 Run case  2:  alpha 5 ail 0                               

 alpha        ->  alpha       =   5.00000    
 beta         ->  beta        =   0.00000    
 pb/2V        ->  pb/2V       =   0.00000    
 qc/2V        ->  qc/2V       =   0.00000    
 rb/2V        ->  rb/2V       =   0.00000    
 aileron      ->  aileron     =   0.00000    

 ---------------------------------------------
 Run case  3:  alpha 0 ail 10                               

 alpha        ->  alpha       =   0.00000    
 beta         ->  beta        =   0.00000    
 pb/2V        ->  pb/2V       =   0.00000    
 qc/2V        ->  qc/2V       =   0.00000    
 rb/2V        ->  rb/2V       =   0.00000    
 aileron      ->  aileron     =   10.0000    
 
  ---------------------------------------------
 Run case  4:  alpha 5 ail 10                               

 alpha        ->  alpha       =   5.00000    
 beta         ->  beta        =   0.00000    
 pb/2V        ->  pb/2V       =   0.00000    
 qc/2V        ->  qc/2V       =   0.00000    
 rb/2V        ->  rb/2V       =   0.00000    
 aileron      ->  aileron     =   10.0000    