/*******************************************************************************
 * <copyright> Copyright (c) 2009-2012 Bauhaus Luftfahrt e.V.. All rights reserved. This program and the accompanying
 *  materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 *  and is available at http://www.eclipse.org/legal/epl-v10.html </copyright>
 ******************************************************************************/

package net.bhl.cdt.architecturetools.model.architecturetools.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.bhl.cdt.architecturetools.model.architecturetools.util.ArchitecturetoolsAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers. The adapters generated by this factory convert EMF adapter
 * notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The
 * adapters also support Eclipse property sheets. Note that most of the adapters
 * are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * 
 * @generated
 */
public class ArchitecturetoolsItemProviderAdapterFactory extends
		ArchitecturetoolsAdapterFactory implements ComposeableAdapterFactory,
		IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this
	 * adapter factory. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement
	 * {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by
	 * {@link #isFactoryForType isFactoryForType}. <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * 
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 * 
	 * @generated
	 */
	public ArchitecturetoolsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.PowerConsumer}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected PowerConsumerItemProvider powerConsumerItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.PowerConsumer}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createPowerConsumerAdapter() {
		if (powerConsumerItemProvider == null) {
			powerConsumerItemProvider = new PowerConsumerItemProvider(this);
		}

		return powerConsumerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.PowerDemandView}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected PowerDemandViewItemProvider powerDemandViewItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.PowerDemandView}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createPowerDemandViewAdapter() {
		if (powerDemandViewItemProvider == null) {
			powerDemandViewItemProvider = new PowerDemandViewItemProvider(this);
		}

		return powerDemandViewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.Massive}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected MassiveItemProvider massiveItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.Massive}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createMassiveAdapter() {
		if (massiveItemProvider == null) {
			massiveItemProvider = new MassiveItemProvider(this);
		}

		return massiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.CoefficientInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected CoefficientInterfaceItemProvider coefficientInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.CoefficientInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createCoefficientInterfaceAdapter() {
		if (coefficientInterfaceItemProvider == null) {
			coefficientInterfaceItemProvider = new CoefficientInterfaceItemProvider(
					this);
		}

		return coefficientInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.WettedAreaInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WettedAreaInterfaceItemProvider wettedAreaInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.WettedAreaInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createWettedAreaInterfaceAdapter() {
		if (wettedAreaInterfaceItemProvider == null) {
			wettedAreaInterfaceItemProvider = new WettedAreaInterfaceItemProvider(
					this);
		}

		return wettedAreaInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.ReferenceAreaInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ReferenceAreaInterfaceItemProvider referenceAreaInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.ReferenceAreaInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createReferenceAreaInterfaceAdapter() {
		if (referenceAreaInterfaceItemProvider == null) {
			referenceAreaInterfaceItemProvider = new ReferenceAreaInterfaceItemProvider(
					this);
		}

		return referenceAreaInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.AltitudeInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected AltitudeInterfaceItemProvider altitudeInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.AltitudeInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createAltitudeInterfaceAdapter() {
		if (altitudeInterfaceItemProvider == null) {
			altitudeInterfaceItemProvider = new AltitudeInterfaceItemProvider(
					this);
		}

		return altitudeInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.RangeInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected RangeInterfaceItemProvider rangeInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.RangeInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createRangeInterfaceAdapter() {
		if (rangeInterfaceItemProvider == null) {
			rangeInterfaceItemProvider = new RangeInterfaceItemProvider(this);
		}

		return rangeInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.SFCInterface}
	 * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected SFCInterfaceItemProvider sfcInterfaceItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link net.bhl.cdt.architecturetools.model.architecturetools.SFCInterface}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createSFCInterfaceAdapter() {
		if (sfcInterfaceItemProvider == null) {
			sfcInterfaceItemProvider = new SFCInterfaceItemProvider(this);
		}

		return sfcInterfaceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory
				.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void setParentAdapterFactory(
			ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the
	 * adapter. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>)
					|| (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to
	 * {@link #parentAdapterFactory}. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 * 
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	public void dispose() {
		if (powerConsumerItemProvider != null)
			powerConsumerItemProvider.dispose();
		if (powerDemandViewItemProvider != null)
			powerDemandViewItemProvider.dispose();
		if (massiveItemProvider != null)
			massiveItemProvider.dispose();
		if (coefficientInterfaceItemProvider != null)
			coefficientInterfaceItemProvider.dispose();
		if (wettedAreaInterfaceItemProvider != null)
			wettedAreaInterfaceItemProvider.dispose();
		if (referenceAreaInterfaceItemProvider != null)
			referenceAreaInterfaceItemProvider.dispose();
		if (altitudeInterfaceItemProvider != null)
			altitudeInterfaceItemProvider.dispose();
		if (rangeInterfaceItemProvider != null)
			rangeInterfaceItemProvider.dispose();
		if (sfcInterfaceItemProvider != null)
			sfcInterfaceItemProvider.dispose();
	}

}
