<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="functions"
    nsURI="http://bhl.net/cdt/calculationrepository/functions" nsPrefix="net.bhl.cdt.calculationrepository">
  <eClassifiers xsi:type="ecore:EClass" name="Function" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputDescriptors" upperBound="-1"
        eType="ecore:EClass ../../net.bhl.cdt.utilities/model/basecalculationmodel.ecore#//ParameterDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDescriptors" upperBound="-1"
        eType="ecore:EClass ../../net.bhl.cdt.utilities/model/basecalculationmodel.ecore#//ParameterDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synopsis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculationScript" abstract="true" eSuperTypes="#//Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScilabFunction" eSuperTypes="#//CalculationScript">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionCall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionReturn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculationRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
