<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.bauhaus-luftfahrt.net/cdt" nsPrefix="net.bhl.cdt">
  <eSubpackages name="base" nsURI="http://www.bauhaus-luftfahrt.net/cdt/base" nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EClass" name="ANamedItem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AIdentifiableItem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelContainer" eSuperTypes="#//base/ANamedItem #//base/AIdentifiableItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedItems" upperBound="-1"
          eType="#//base/AModelContainerItem" containment="true" eOpposite="#//base/AModelContainerItem/container"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantitySet" eType="#//science/QuantitySet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AModelContainerItem" abstract="true"
        eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//base/ModelContainer" eOpposite="#//base/ModelContainer/containedItems"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="science" nsURI="http://www.bauhaus-luftfahrt.net/cdt/science"
      nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EClass" name="QuantitySet" eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantityKinds" upperBound="-1"
          eType="#//science/QuantityKind" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuantityKind" abstract="true" eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
          containment="true">
        <eGenericType eClassifier="#//science/Unit">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true" eSuperTypes="#//base/ANamedItem">
      <eTypeParameters name="Q">
        <eBounds eClassifier="#//science/QuantityKind"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDataEntity" abstract="true" interface="true"
        eSuperTypes="#//base/AIdentifiableItem #//base/ANamedItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//science/IParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IParameter" abstract="true" interface="true"
        eSuperTypes="#//base/ANamedItem #//base/AIdentifiableItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="IQuantifiedParameter" abstract="true"
        interface="true" eSuperTypes="#//science/IParameter">
      <eTypeParameters name="Q">
        <eBounds eClassifier="#//science/QuantityKind"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1">
        <eGenericType eClassifier="#//science/Unit">
          <eTypeArguments eTypeParameter="#//science/IQuantifiedParameter/Q"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantity" lowerBound="1">
        <eGenericType eTypeParameter="#//science/IQuantifiedParameter/Q"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="quantities" nsURI="http://www.bauhaus-luftfahrt.net/cdt/data/quantities"
        nsPrefix="net.bhl.cdt.model.data">
      <eClassifiers xsi:type="ecore:EClass" name="Distance" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Time" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Velocity" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Mass" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Force" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Efficiency" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Energy" eSuperTypes="#//science/QuantityKind"/>
      <eClassifiers xsi:type="ecore:EClass" name="Power" eSuperTypes="#//science/QuantityKind"/>
    </eSubpackages>
    <eSubpackages name="parameter" nsURI="http://www.bauhaus-luftfahrt.net/cdt/data/parameter"
        nsPrefix="net.bhl.cdt.model.data">
      <eClassifiers xsi:type="ecore:EClass" name="StringParameter" eSuperTypes="#//science/IParameter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DateParameter" eSuperTypes="#//science/IParameter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DistanceParameter">
        <eGenericSuperTypes eClassifier="#//science/IQuantifiedParameter">
          <eTypeArguments eClassifier="#//science/quantities/Distance"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimeParameter">
        <eGenericSuperTypes eClassifier="#//science/IQuantifiedParameter">
          <eTypeArguments eClassifier="#//science/quantities/Time"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="unit" nsURI="http://www.bauhaus-luftfahrt.net/cdt/data/unit"
        nsPrefix="net.bhl.cdt.model.data">
      <eClassifiers xsi:type="ecore:EClass" name="DistanceUnit">
        <eGenericSuperTypes eClassifier="#//science/Unit">
          <eTypeArguments eClassifier="#//science/quantities/Distance"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimeUnit">
        <eGenericSuperTypes eClassifier="#//science/Unit">
          <eTypeArguments eClassifier="#//science/quantities/Time"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MassUnit">
        <eGenericSuperTypes eClassifier="#//science/Unit">
          <eTypeArguments eClassifier="#//science/quantities/Mass"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="engineering" nsURI="http://www.bauhaus-luftfahrt.net/cdt/engineering"
      nsPrefix="net.bhl.cdt.model">
    <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//base/AModelContainerItem #//science/IDataEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//engineering/Component" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//science/IDataEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingComponent"
          eType="#//engineering/Component" eOpposite="#//engineering/Component/subComponents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
          eType="#//engineering/Component" containment="true" eOpposite="#//engineering/Component/containingComponent"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
