<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://bhl.net/cdt/model" nsPrefix="net.bhl.cdt.model">
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//StructuralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedComponents" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//StructuralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="datatypes.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//Configuration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//StructuralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass datatypes.ecore#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultUnit" eType="ecore:EDataType units.ecore#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralElement" abstract="true" eSuperTypes="datatypes.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="datatypes.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass datatypes.ecore#//DataType"/>
  </eClassifiers>
</ecore:EPackage>
