<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="units" nsURI="http://bhl.net/cdt/model/units" nsPrefix="net.bhl.cdt.model">
  <eClassifiers xsi:type="ecore:EDataType" name="Unit" instanceClassName="javax.measure.unit.Unit">
    <eTypeParameters name="Q">
      <eBounds eClassifier="#//Quantity"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Quantity" instanceClassName="javax.measure.quantity.Quantity"/>
</ecore:EPackage>
